create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, module_slug, lesson_slug)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  score integer not null default 0,
  total_questions integer not null default 0,
  matched_count integer not null default 0,
  passed boolean not null default false,
  answers jsonb not null default '{}'::jsonb,
  feedback jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.project_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  title text not null,
  repo_url text not null,
  live_url text,
  notes text,
  status text not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module_slug, lesson_slug)
);

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.project_submissions enable row level security;

create policy "Profiles are readable by their owner"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Profiles are insertable by their owner"
  on public.profiles
  for insert
  with check (auth.uid() = id);

create policy "Profiles are updateable by their owner"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can read their lesson progress"
  on public.lesson_progress
  for select
  using (auth.uid() = user_id);

create policy "Users can upsert their lesson progress"
  on public.lesson_progress
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their quiz attempts"
  on public.quiz_attempts
  for select
  using (auth.uid() = user_id);

create policy "Users can add quiz attempts"
  on public.quiz_attempts
  for insert
  with check (auth.uid() = user_id);

create policy "Users can read their project submissions"
  on public.project_submissions
  for select
  using (auth.uid() = user_id);

create policy "Users can submit and update their project submissions"
  on public.project_submissions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
