create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lesson_progress (
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  completed boolean not null default false,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, module_slug, lesson_slug)
);

create table if not exists public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  score integer not null default 0,
  total_questions integer not null default 0,
  matched_count integer not null default 0,
  passed boolean not null default false,
  answers jsonb not null default '{}'::jsonb,
  feedback jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.project_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  lesson_slug text not null,
  title text not null,
  repo_url text not null,
  live_url text,
  notes text,
  skills text[] default '{}',
  technical_writeup text,
  reflection text,
  status text not null default 'submitted',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module_slug, lesson_slug)
);

create table if not exists public.boss_battle_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module_slug text not null,
  boss_battle_slug text not null,
  response text,
  completed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module_slug, boss_battle_slug)
);

alter table public.project_submissions
  add column if not exists skills text[] default '{}';
alter table public.project_submissions
  add column if not exists technical_writeup text;
alter table public.project_submissions
  add column if not exists reflection text;

create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  entity_type text not null,
  entity_id text not null,
  xp_amount integer not null check (xp_amount > 0),
  created_at timestamptz not null default now(),
  unique (user_id, event_type, entity_type, entity_id)
);

create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_xp integer not null default 0 check (total_xp >= 0),
  current_level integer not null default 1 check (current_level >= 1),
  current_streak integer not null default 0 check (current_streak >= 0),
  longest_streak integer not null default 0 check (longest_streak >= 0),
  last_activity_date date,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  achievement_id text not null,
  unlocked_at timestamptz not null default now(),
  unique (user_id, achievement_id)
);

create or replace function public.touch_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row
execute procedure public.touch_updated_at();

drop trigger if exists set_lesson_progress_updated_at on public.lesson_progress;
create trigger set_lesson_progress_updated_at
before update on public.lesson_progress
for each row
execute procedure public.touch_updated_at();

drop trigger if exists set_project_submissions_updated_at on public.project_submissions;
create trigger set_project_submissions_updated_at
before update on public.project_submissions
for each row
execute procedure public.touch_updated_at();

drop trigger if exists set_boss_battle_progress_updated_at on public.boss_battle_progress;
create trigger set_boss_battle_progress_updated_at
before update on public.boss_battle_progress
for each row
execute procedure public.touch_updated_at();

drop trigger if exists set_user_stats_updated_at on public.user_stats;
create trigger set_user_stats_updated_at
before update on public.user_stats
for each row
execute procedure public.touch_updated_at();

create or replace function public.ai_foundry_level_for_xp(total_xp integer)
returns integer as $$
begin
  return case
    when total_xp >= 35000 then 20
    when total_xp >= 20000 then 15
    when total_xp >= 12000 then 10
    when total_xp >= 8500 then 9
    when total_xp >= 6000 then 8
    when total_xp >= 4200 then 7
    when total_xp >= 2800 then 6
    when total_xp >= 1800 then 5
    when total_xp >= 1000 then 4
    when total_xp >= 500 then 3
    when total_xp >= 200 then 2
    else 1
  end;
end;
$$ language plpgsql immutable;

create or replace function public.award_xp_event(
  p_event_type text,
  p_entity_type text,
  p_entity_id text,
  p_xp_amount integer
)
returns boolean as $$
declare
  inserted_event record;
  existing_stats record;
  next_total_xp integer;
  next_streak integer;
  today date := current_date;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if p_xp_amount <= 0 then
    raise exception 'xp_amount_must_be_positive';
  end if;

  insert into public.xp_events (
    user_id,
    event_type,
    entity_type,
    entity_id,
    xp_amount
  )
  values (
    auth.uid(),
    p_event_type,
    p_entity_type,
    p_entity_id,
    p_xp_amount
  )
  on conflict (user_id, event_type, entity_type, entity_id) do nothing
  returning * into inserted_event;

  if inserted_event is null then
    return false;
  end if;

  select *
  into existing_stats
  from public.user_stats
  where user_id = auth.uid()
  for update;

  if existing_stats is null then
    next_total_xp := p_xp_amount;
    next_streak := 1;
  else
    next_total_xp := existing_stats.total_xp + p_xp_amount;
    next_streak := case
      when existing_stats.last_activity_date = today then existing_stats.current_streak
      when existing_stats.last_activity_date = today - 1 then existing_stats.current_streak + 1
      else 1
    end;
  end if;

  insert into public.user_stats (
    user_id,
    total_xp,
    current_level,
    current_streak,
    longest_streak,
    last_activity_date
  )
  values (
    auth.uid(),
    next_total_xp,
    public.ai_foundry_level_for_xp(next_total_xp),
    next_streak,
    next_streak,
    today
  )
  on conflict (user_id) do update set
    total_xp = excluded.total_xp,
    current_level = excluded.current_level,
    current_streak = excluded.current_streak,
    longest_streak = greatest(public.user_stats.longest_streak, excluded.current_streak),
    last_activity_date = excluded.last_activity_date,
    updated_at = now();

  return true;
end;
$$ language plpgsql security definer set search_path = public;

create index if not exists lesson_progress_user_idx
  on public.lesson_progress(user_id);
create index if not exists quiz_attempts_user_idx
  on public.quiz_attempts(user_id);
create index if not exists project_submissions_user_idx
  on public.project_submissions(user_id);
create index if not exists xp_events_user_idx
  on public.xp_events(user_id);
create index if not exists user_achievements_user_idx
  on public.user_achievements(user_id);

alter table public.project_submissions
  add constraint project_submissions_status_check
  check (status in ('submitted', 'reviewed', 'needs_work'));

do $$
begin
  if not exists (
    select 1
    from pg_indexes
    where schemaname = 'public'
      and indexname = 'quiz_attempts_module_lesson_user_desc_idx'
  ) then
    create index quiz_attempts_module_lesson_user_desc_idx
      on public.quiz_attempts (user_id, module_slug, lesson_slug, created_at desc);
  end if;
end
$$;

alter table public.profiles enable row level security;
alter table public.lesson_progress enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.project_submissions enable row level security;
alter table public.boss_battle_progress enable row level security;
alter table public.xp_events enable row level security;
alter table public.user_stats enable row level security;
alter table public.user_achievements enable row level security;

create policy "Profiles are readable by their owner"
  on public.profiles
  for select
  using (auth.uid() = id);

create policy "Profiles are insertable by their owner"
  on public.profiles
  for insert
  with check (auth.uid() = id);

create policy "Profiles are updateable by their owner"
  on public.profiles
  for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

create policy "Users can read their lesson progress"
  on public.lesson_progress
  for select
  using (auth.uid() = user_id);

create policy "Users can upsert their lesson progress"
  on public.lesson_progress
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their quiz attempts"
  on public.quiz_attempts
  for select
  using (auth.uid() = user_id);

create policy "Users can add quiz attempts"
  on public.quiz_attempts
  for insert
  with check (auth.uid() = user_id);

create policy "Users can read their project submissions"
  on public.project_submissions
  for select
  using (auth.uid() = user_id);

create policy "Users can submit and update their project submissions"
  on public.project_submissions
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their boss battle progress"
  on public.boss_battle_progress
  for select
  using (auth.uid() = user_id);

create policy "Users can submit their boss battle progress"
  on public.boss_battle_progress
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their XP events"
  on public.xp_events
  for select
  using (auth.uid() = user_id);

create policy "Users can add their XP events"
  on public.xp_events
  for insert
  with check (auth.uid() = user_id);

create policy "Users can read their stats"
  on public.user_stats
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their stats"
  on public.user_stats
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their stats"
  on public.user_stats
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read their achievements"
  on public.user_achievements
  for select
  using (auth.uid() = user_id);

create policy "Users can unlock their achievements"
  on public.user_achievements
  for insert
  with check (auth.uid() = user_id);
